version: 2.1

references:
  defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.22.4

  npm_dep_cache_key: &npm_dep_cache_key npm-build-cache-{{ checksum "package.json" }}

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      name: 'Restore cache: npm modules'
      key: *npm_dep_cache_key

  save_npm_cache: &save_npm_cache
    save_cache:
      name: 'Save cache: npm modules'
      key: *npm_dep_cache_key
      paths:
        - node_modules

  install_npm_modules: &install_npm_modules
    run:
      name: Install npm modules
      command: |
        npm install

  run_npm_test: &run_npm_test
    run:
      name: Run npm test
      command: |
        npm run test

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: ~/repo
      paths:
        - .

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_npm_modules
      - *run_npm_test
      - *save_npm_cache
      - *persist_to_workspace

workflows:
  run_test:
    jobs:
      - test
